// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi pinterest-clone API
API spec for pinterest-clone


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/io.goswagger.examples.pinterest-clone.v1+json

    Produces:
    - application/io.goswagger.examples.pinterest-clone.v1+json

swagger:meta
*/
package restapi
