// Code generated by go-swagger; DO NOT EDIT.

package pinterest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFeedParams creates a new FeedParams object
// no default values defined in spec.
func NewFeedParams() FeedParams {

	return FeedParams{}
}

// FeedParams contains all the bound params for the feed operation
// typically these are obtained from a http.Request
//
// swagger:parameters feed
type FeedParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	PinAmount string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewFeedParams() beforehand.
func (o *FeedParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qPinAmount, qhkPinAmount, _ := qs.GetOK("pin_amount")
	if err := o.bindPinAmount(qPinAmount, qhkPinAmount, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPinAmount binds and validates parameter PinAmount from query.
func (o *FeedParams) bindPinAmount(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("pin_amount", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("pin_amount", "query", raw); err != nil {
		return err
	}

	o.PinAmount = raw

	return nil
}
