// Code generated by go-swagger; DO NOT EDIT.

package pinterest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PinHandlerFunc turns a function with the right signature into a pin handler
type PinHandlerFunc func(PinParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PinHandlerFunc) Handle(params PinParams) middleware.Responder {
	return fn(params)
}

// PinHandler interface for that can handle valid pin params
type PinHandler interface {
	Handle(PinParams) middleware.Responder
}

// NewPin creates a new http.Handler for the pin operation
func NewPin(ctx *middleware.Context, handler PinHandler) *Pin {
	return &Pin{Context: ctx, Handler: handler}
}

/*Pin swagger:route GET /pin pinterest pin

Pin pin API

*/
type Pin struct {
	Context *middleware.Context
	Handler PinHandler
}

func (o *Pin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPinParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
