// Code generated by go-swagger; DO NOT EDIT.

package pinterest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PinsHandlerFunc turns a function with the right signature into a pins handler
type PinsHandlerFunc func(PinsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PinsHandlerFunc) Handle(params PinsParams) middleware.Responder {
	return fn(params)
}

// PinsHandler interface for that can handle valid pins params
type PinsHandler interface {
	Handle(PinsParams) middleware.Responder
}

// NewPins creates a new http.Handler for the pins operation
func NewPins(ctx *middleware.Context, handler PinsHandler) *Pins {
	return &Pins{Context: ctx, Handler: handler}
}

/*Pins swagger:route GET /pins pinterest pins

Pins pins API

*/
type Pins struct {
	Context *middleware.Context
	Handler PinsHandler
}

func (o *Pins) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPinsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
