// Code generated by go-swagger; DO NOT EDIT.

package pinterest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UserHandlerFunc turns a function with the right signature into a user handler
type UserHandlerFunc func(UserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UserHandlerFunc) Handle(params UserParams) middleware.Responder {
	return fn(params)
}

// UserHandler interface for that can handle valid user params
type UserHandler interface {
	Handle(UserParams) middleware.Responder
}

// NewUser creates a new http.Handler for the user operation
func NewUser(ctx *middleware.Context, handler UserHandler) *User {
	return &User{Context: ctx, Handler: handler}
}

/*User swagger:route GET /user pinterest user

User user API

*/
type User struct {
	Context *middleware.Context
	Handler UserHandler
}

func (o *User) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
